#!/usr/bin/env python3
"""Generate HA Assist intent YAML files from the Culiplan voice registry.

Source: GET https://api.culiplan.com/api/voice/tools?tag=ha-assist:eligible

Usage:
    python scripts/generate_intents.py
    python scripts/generate_intents.py --api-base https://api.culiplan.com
    python scripts/generate_intents.py --from-fixture scripts/fixtures/ha_tools.json

The generated files land in custom_components/culiplan/intents/{lang}.yaml.
Run this script at release time to keep the committed YAML in sync with the
registry. The script is idempotent: identical inputs produce identical outputs.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

try:
    import requests
except ImportError:
    requests = None  # type: ignore[assignment]

try:
    import yaml as pyyaml
except ImportError:
    pyyaml = None  # type: ignore[assignment]

# ─── Constants ────────────────────────────────────────────────────────────────

LANGUAGES = ["en", "nl", "de", "fr", "es"]
INTENTS_DIR = Path(__file__).parent.parent / "custom_components" / "culiplan" / "intents"
FIXTURES_DIR = Path(__file__).parent / "fixtures"

# Prefix all intent names to avoid collisions in the global HA intent namespace.
INTENT_PREFIX = "Culiplan"

# ─── Main ─────────────────────────────────────────────────────────────────────


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--api-base",
        default="https://api.culiplan.com",
        help="Culiplan API base URL (default: https://api.culiplan.com)",
    )
    parser.add_argument(
        "--from-fixture",
        metavar="FILE",
        help="Load tool list from a JSON fixture instead of the live API",
    )
    args = parser.parse_args()

    tools_by_lang: dict[str, list[dict[str, Any]]] = {}

    if args.from_fixture:
        fixture = json.loads(Path(args.from_fixture).read_text())
        for lang in LANGUAGES:
            tools_by_lang[lang] = fixture.get(lang, fixture.get("en", []))
    else:
        if requests is None:
            print("ERROR: 'requests' package not installed. Run: pip install requests", file=sys.stderr)
            return 1
        tools_by_lang = _fetch_from_api(args.api_base)

    INTENTS_DIR.mkdir(parents=True, exist_ok=True)
    for lang in LANGUAGES:
        tools = tools_by_lang.get(lang, [])
        yaml_text = _render_yaml(lang, tools)
        out = INTENTS_DIR / f"{lang}.yaml"
        out.write_text(yaml_text, encoding="utf-8")
        print(f"  Written {out.relative_to(Path.cwd())}")

    print("Done.")
    return 0


def _fetch_from_api(api_base: str) -> dict[str, list[dict[str, Any]]]:
    """Fetch the ha-assist:eligible tool list for each language from the live API."""
    result: dict[str, list[dict[str, Any]]] = {}
    for lang in LANGUAGES:
        url = f"{api_base}/api/voice/tools?tag=ha-assist:eligible&lang={lang}"
        print(f"  Fetching {url} …")
        resp = requests.get(url, timeout=15)  # type: ignore[union-attr]
        resp.raise_for_status()
        result[lang] = resp.json()
    return result


def _render_yaml(lang: str, tools: list[dict[str, Any]]) -> str:
    """Convert a list of tool descriptors into HA custom-sentences YAML."""
    lines: list[str] = [
        f"# Auto-generated by scripts/generate_intents.py — do not edit manually.",
        f"# Source: api.culiplan.com/api/voice/tools?tag=ha-assist:eligible&lang={lang}",
        f"language: \"{lang}\"",
        "intents:",
    ]

    response_lines: list[str] = ["responses:", "  intents:"]

    for tool in tools:
        intent_name = f"{INTENT_PREFIX}{_to_pascal(tool['intentId'])}"
        phrases = tool.get("triggerPhrases", [])
        response = tool.get("responseTemplate", "{{ response }}")

        lines.append(f"  {intent_name}:")
        lines.append(f"    data:")
        lines.append(f"      - sentences:")

        for phrase in phrases:
            # Convert {slot} → (slot) for HA sentence syntax.
            ha_phrase = _to_ha_sentence(phrase)
            lines.append(f"          - \"{ha_phrase}\"")

        # Slots
        params = tool.get("parameters", {})
        if params:
            lines.append(f"        slots:")
            for slot_name in params:
                lines.append(f"          {slot_name}: \"{{{slot_name}}}\"")

        response_lines.append(f"    {intent_name}: \"{response}\"")

    return "\n".join(lines + [""] + response_lines + [""])


def _to_pascal(snake: str) -> str:
    """Convert snake_case to PascalCase."""
    return "".join(word.title() for word in snake.split("_"))


def _to_ha_sentence(phrase: str) -> str:
    """Convert backend phrase template {slot} to HA sentence syntax {slot}."""
    # HA uses {slot} for wildcard slots — same as backend. No transform needed.
    # Escape double-quotes for YAML embedding.
    return phrase.replace('"', '\\"')


if __name__ == "__main__":
    sys.exit(main())
